language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
install:
  - "pip install -e .'[dev]'"
script: 'py.test'
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database pianodb_test;'
  - psql -c 'create database pianodb_test;' -U postgres
