language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
install:
  - 'pip install .'
  - 'pip install -r dev-requirements.txt'
script: 'py.test -v'
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database pianodb_test;'
  - psql -c 'create database pianodb_test;' -U postgres
