language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
env:
  global:
    - NEWEST_PYTHON=3.5
install:
  - "pip install -e .'[dev]'"
script: 'py.test'
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database pianodb_test;'
  - psql -c 'create database pianodb_test;' -U postgres
after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then
      pip install python-coveralls && coveralls
    fi
